services:
    app:
        container_name: app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
            # - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        ports:
            - "8080:8080"
        tty: true
        networks:
            - laravel
        depends_on:
            - db
            - elasticsearch

    db:
        image: postgres:16-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            PGDATA: /data/postgres
            TZ: Asia/Tashkent
        ports:
            - "5432:5432"
        volumes:
            - postgresql:/data/postgres
        networks:
            - laravel


    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
        container_name: elasticsearch
        restart: unless-stopped
        environment:
            - node.name=elastic-node
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
            - xpack.security.autoconfiguration.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            - laravel


volumes:
    postgresql:
        driver: local
    es-data:
        driver: local

networks:
    laravel:
        driver: bridge
